### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by cpdef** [devenlil/Bliep.io-Server#1]
@devenlil Please add installation instructions for the server! 
i wanna try this game :)
And if it doesn't work out of the box, please add also instructions to 
join the server, which i create then.

I could provide for first tests also an public server on my raspberry pi

**Comment by devenlil** [comment]
_I will add these instructions (or slightly updated ones) in the `README.md` later._
The Bliep.io Server is very easy to install, especially if you already have node & npm installed on your server. If you do not have these installed, you can search the web for instructions for your particular system. I'm sure their are a lot of thorough tutorials available on this topic. If you are using a mac or windows personal computer, the easiest way to install node/npm is from [here](https://nodejs.org/en/).

## **Installing Bliep.io Server**

1. Download repository and extract zip.
2. With terminal or command prompt cd to the base directory (should contain the `src` folder and `package.json`)
Ex. `cd C:\Users\xxxx\Desktop\Bliep.io-Server\`
3. Type in `npm install`.
4. If you get any installation error about `memwatch` do the following and then redo step 3:
(a) In the file `package.json` remove the line `"memwatch-next": "latest"` and remove the comma from the line `"ws": "latest",` so that it looks like this: `"ws": "latest"`.
(b) Navigate to `src` folder and in `app.js` remove the line `memwatch.on('leak', function(info) {` and all the other lines beneath that.

## **Starting the server**
Start the server by the `npm start` command while you are in the base directory.

## **Using the client**
- You might have to use a web server to access the client. Simply double clicking on index.html and opening directly may not work.
- By default the client connects to the local server (127.0.0.1:8080). To change this you must edit the servers.json in the game folder on the client. If you change the port remember to also change it in the config file on the server.


Thank you for your interest!
Remember this project is far from complete. Many features don't work, including collision detection. Don't critique it too much!

**Comment by cpdef** [comment]
thx :) btw. i use linux and yeah i know its not complete :)

**Comment by devenlil** [comment]
No problem! I use linux (Ubuntu) too for developing this. Anyways, did you figure out everything?

**Comment by cpdef** [comment]
I had problems finding the npm-containing package, but now i'am installing npm+node.js

**Comment by cpdef** [comment]
ok finished installing and testing :)
